// THIS FILE IS AUTOGENERATED. TO UPDATE, RUN
//    dart tool/generate_asset_hashes.dart

const assetHashes = <String, String>{
  'libpixer_android_arm64.so': '094e19250c384452c1a30b952941b737',
  'libpixer_android_armv7.so': 'f0c6c9968f7cfc731d50da7ec0d384f7',
  'libpixer_android_x86_64.so': 'a52d24c5e50544d04018f0e7b881a08c',
  'libpixer_ios_arm64.dylib': 'fb9a24aed00a9617618392381556c354',
  'libpixer_ios_sim_arm64.dylib': '99b99de97242b99803f6b9468f12da4a',
  'libpixer_ios_sim_x86_64.dylib': 'bf3387cff60a33b378b78634ebf1dbdd',
  'libpixer_linux_aarch64.so': '677168bc65b7608b6a82565bf1754bcf',
  'libpixer_linux_x86_64.so': 'e72ffbdf156960e4eddb2eadad6c3382',
  'libpixer_macos_arm64.dylib': '6f15c59c28f13cefe4ad626d23e4634b',
  'libpixer_macos_x86_64.dylib': 'a388c225db38fbe487f53fd08dc61290',
  'pixer_windows_arm64.dll': 'ab78f466051834e9e6d1dc9bfdca18b8',
  'pixer_windows_x86_64.dll': '7128c9973dad6f13af13975e3b9ccd69',
};
